"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import s from "./BearSmash.module.css";
type K="bear"|"fast"|"tank"|"gold"|"bull";type T={id:number;hole:number;kind:K;hp:number;born:number;ttl:number};
const holes=[0,1,2,3,4,5,6,7,8],data:Record<K,{p:number;hp:number}>={bear:{p:100,hp:1},fast:{p:250,hp:1},tank:{p:180,hp:3},gold:{p:1000,hp:1},bull:{p:-500,hp:1}};
function kind(t:number):K{const r=Math.random();return r<.06?"gold":r<.16?"bull":r<.29&&t>10?"tank":r<.5&&t>5?"fast":"bear"}
export default function BearSmash(){
 const [playing,setPlaying]=useState(false),[targets,setTargets]=useState<T[]>([]),[score,setScore]=useState(0),[best,setBest]=useState(0),[combo,setCombo]=useState(0),[lives,setLives]=useState(3),[charge,setCharge]=useState(0),[time,setTime]=useState(60),[flash,setFlash]=useState("READY?");
 const tr=useRef<T[]>([]),sr=useRef(0),cr=useRef(0),lr=useRef(3),chr=useRef(0),start=useRef(0),id=useRef(1),play=useRef(false);
 const update=useCallback((x:T[])=>{tr.current=x;setTargets(x)},[]);const finish=useCallback(()=>{play.current=false;setPlaying(false);update([]);setFlash("ROUND OVER");setBest(b=>{const n=Math.max(b,sr.current);localStorage.setItem("bulle-bear-best",String(n));return n})},[update]);
 useEffect(()=>setBest(Number(localStorage.getItem("bulle-bear-best")||0)),[]);
 useEffect(()=>{if(!playing)return;const x=setInterval(()=>{const left=Math.max(0,Math.ceil(60-(Date.now()-start.current)/1000));setTime(left);if(!left)finish()},100);return()=>clearInterval(x)},[playing,finish]);
 useEffect(()=>{if(!playing)return;const x=setInterval(()=>{const elapsed=(Date.now()-start.current)/1000,free=holes.filter(h=>!tr.current.some(t=>t.hole===h));if(!free.length)return;const k=kind(elapsed),ttl=k==="fast"?600:k==="gold"?720:Math.max(780,1350-elapsed*7);update([...tr.current,{id:id.current++,hole:free[Math.floor(Math.random()*free.length)],kind:k,hp:data[k].hp,born:Date.now(),ttl}])},510);return()=>clearInterval(x)},[playing,update]);
 useEffect(()=>{if(!playing)return;const x=setInterval(()=>{const now=Date.now(),expired=tr.current.filter(t=>now-t.born>=t.ttl);if(!expired.length)return;update(tr.current.filter(t=>now-t.born<t.ttl));if(expired.some(t=>t.kind!=="bull")){cr.current=0;setCombo(0);lr.current--;setLives(Math.max(0,lr.current));setFlash("MISSED!");if(lr.current<=0)finish()}},80);return()=>clearInterval(x)},[playing,update,finish]);
 function begin(){sr.current=cr.current=chr.current=0;lr.current=3;start.current=Date.now();play.current=true;setScore(0);setCombo(0);setCharge(0);setLives(3);setTime(60);setFlash("SMASH!");update([]);setPlaying(true)}
 function hit(t:T){if(!play.current)return;if(t.kind==="bull"){sr.current=Math.max(0,sr.current-500);setScore(sr.current);update(tr.current.filter(x=>x.id!==t.id));cr.current=0;setCombo(0);lr.current--;setLives(Math.max(0,lr.current));setFlash("PROTECT BULLE!");if(lr.current<=0)finish();return}if(t.hp>1){update(tr.current.map(x=>x.id===t.id?{...x,hp:x.hp-1,born:Date.now(),ttl:700}:x));setFlash(`${t.hp-1} HIT LEFT!`);return}cr.current++;const m=Math.min(5,1+Math.floor(cr.current/5)),pts=data[t.kind].p*m;sr.current+=pts;chr.current=Math.min(100,chr.current+(t.kind==="gold"?35:11));setScore(sr.current);setCombo(cr.current);setCharge(chr.current);setFlash(t.kind==="gold"?`JACKPOT +${pts}`:`BAM! +${pts}`);update(tr.current.filter(x=>x.id!==t.id))}
 function stampede(){if(chr.current<100)return;const b=tr.current.filter(t=>t.kind!=="bull"),pts=b.reduce((a,t)=>a+data[t.kind].p,500);sr.current+=pts;chr.current=0;setScore(sr.current);setCharge(0);setFlash(`STAMPEDE! +${pts}`);update(tr.current.filter(t=>t.kind==="bull"));navigator.vibrate?.([80,40,120])}
 return <section className={s.wrap}><div className={s.stats}><div><small>SCORE</small><b>{score.toLocaleString()}</b></div><div><small>COMBO</small><b>×{Math.min(5,1+Math.floor(combo/5))}</b></div><div><small>TIME</small><b>{time}s</b></div><div><small>ENERGY</small><b>{"●".repeat(lives)}{"○".repeat(3-lives)}</b></div></div><div className={s.arena}><div className={s.flash} key={flash}>{flash}</div><div className={s.bull}><img src="/bulle-logo.jpg" alt="Cyber Bull"/><b>CYBER BULL</b></div><div className={s.grid}>{holes.map(h=>{const t=targets.find(x=>x.hole===h);return <button type="button" key={h} className={s.hole} onPointerDown={()=>t&&hit(t)}>{t&&<span className={`${s.target} ${s[t.kind]}`}><i/><i/><strong>{t.kind==="bull"?"BULLE":t.kind.toUpperCase()}</strong>{t.kind==="tank"&&<em>{t.hp}×</em>}</span>}</button>})}</div>{!playing&&<div className={s.overlay}><small>60 SECOND SKILL CHALLENGE</small><h2>{score?"ROUND COMPLETE":"BEAR SMASH"}</h2>{score>0&&<b>{score.toLocaleString()} POINTS</b>}<p>Smash the bears. Protect Cyber Bull. Build combos and unleash Stampede Mode.</p><button type="button" onClick={begin}>{score?"PLAY AGAIN":"ENTER THE RING"}</button><span>PERSONAL BEST: {best.toLocaleString()}</span></div>}</div><div className={s.charge}><div><span style={{width:`${charge}%`}}/></div><button type="button" disabled={charge<100||!playing} onClick={stampede}>UNLEASH STAMPEDE</button></div><footer>BEAR +100 · FAST +250 · GOLD +1,000 · PROTECT BULLE</footer></section>
}
