"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import bs58 from "bs58";
import s from "./BearSmashV16.module.css";
import WalletPicker from "./WalletPicker";
import PlayerProfileSetup,{LocalPlayerProfile,readLocalProfile} from "./PlayerProfileSetup";
import type {BrowserWalletProvider} from "../lib/clientWallet";

type Tab="play"|"ranking"|"workshop"|"profile";type Mode="story"|"tournament";type Kind="bear"|"fast"|"tank"|"gold"|"ally";
type Target={id:number;hole:number;kind:Kind;hp:number;born:number;ttl:number};
type Item={id:string;name:string;cost:number;power:number;rarity:string;color:string};
type Save={bullPoints:number;rewardPoints:number;totalPoints:number;storyGames:number;storyBest:number;skin:string;hammer:string;ownedSkins:string[];ownedHammers:string[];tournamentDate:string;tournamentPlays:number;tournamentBest:number};
type RewardPool={wallet:string;mint:string;balanceBulle:number;balanceSol:number;priceUsd:number;valueUsd:number;funded:boolean;payerWallet:string;payerBalanceBulle:number;payerBalanceSol:number;payerFunded:boolean;payoutEnabled:boolean;updatedAt:string};
const SAVE_KEY="bulle-bear-smash-v16",GAME_SECONDS=60,HOLES=[0,1,2,3,4,5,6,7,8];
const today=()=>new Date().toLocaleDateString("en-CA");
const skins:Item[]=[{id:"steel",name:"Steel Bull",cost:0,power:1,rarity:"COMMON",color:"#aab5ad"},{id:"neon",name:"Neon Bull",cost:350,power:1.1,rarity:"RARE",color:"#8dff2f"},{id:"solana",name:"Solana Bull",cost:850,power:1.2,rarity:"EPIC",color:"#a970ff"},{id:"gold",name:"Diamond Bull",cost:1600,power:1.35,rarity:"LEGENDARY",color:"#7cecff"}];
const hammers:Item[]=[{id:"rookie",name:"Rookie Hammer",cost:0,power:1,rarity:"COMMON",color:"#aab5ad"},{id:"turbo",name:"Turbo Hammer",cost:250,power:1.08,rarity:"RARE",color:"#40d9ff"},{id:"titan",name:"Titan Crusher",cost:700,power:1.18,rarity:"EPIC",color:"#ff7048"},{id:"stampede",name:"Stampede Maul",cost:1400,power:1.3,rarity:"LEGENDARY",color:"#8dff2f"}];
const defaultSave:Save={bullPoints:0,rewardPoints:0,totalPoints:0,storyGames:0,storyBest:0,skin:"steel",hammer:"rookie",ownedSkins:["steel"],ownedHammers:["rookie"],tournamentDate:today(),tournamentPlays:0,tournamentBest:0};
const base:Record<Kind,{points:number;hp:number;label:string}>={bear:{points:10,hp:1,label:"BEAR"},fast:{points:25,hp:1,label:"FAST"},tank:{points:18,hp:3,label:"TANK"},gold:{points:100,hp:1,label:"GOLD"},ally:{points:-50,hp:1,label:"BULLE"}};
function chooseKind(elapsed:number):Kind{const r=Math.random();return r<.06?"gold":r<.15?"ally":r<.29&&elapsed>10?"tank":r<.5&&elapsed>5?"fast":"bear"}
function levelFor(games:number){return Math.floor(games/3)+1}function rankFor(level:number){return level>=15?"STAMPEDE LEGEND":level>=10?"ALPHA BULL":level>=6?"ARENA CHAMPION":level>=3?"BULL FIGHTER":"ROOKIE HORN"}

export default function BearSmashV16(){
 const [tab,setTab]=useState<Tab>("play"),[mode,setMode]=useState<Mode>("story"),[save,setSave]=useState<Save>(defaultSave),[ready,setReady]=useState(false);
 const [playing,setPlaying]=useState(false),[targets,setTargets]=useState<Target[]>([]),[score,setScore]=useState(0),[combo,setCombo]=useState(0),[lives,setLives]=useState(3),[charge,setCharge]=useState(0),[time,setTime]=useState(GAME_SECONDS),[flash,setFlash]=useState("READY?"),[arenaIndex,setArenaIndex]=useState(0),[impact,setImpact]=useState<number|null>(null),[musicOn,setMusicOn]=useState(false);
 const [walletPickerOpen,setWalletPickerOpen]=useState(false),[profileWallet,setProfileWallet]=useState(""),[playerProfile,setPlayerProfile]=useState<LocalPlayerProfile|null>(null),[walletAddress,setWalletAddress]=useState("");
 const [walletProvider,setWalletProvider]=useState<BrowserWalletProvider|null>(null),[rewardPool,setRewardPool]=useState<RewardPool|null>(null),[claimBusy,setClaimBusy]=useState(false),[claimMessage,setClaimMessage]=useState("");
 const tr=useRef<Target[]>([]),sr=useRef(0),cr=useRef(0),lr=useRef(3),chr=useRef(0),startR=useRef(0),idR=useRef(1),playR=useRef(false),modeR=useRef<Mode>("story");
 const audioR=useRef<AudioContext|null>(null),musicTimerR=useRef<number|null>(null),musicStepR=useRef(0);
 const level=levelFor(save.storyGames),skin=skins.find(x=>x.id===save.skin)??skins[0],hammer=hammers.find(x=>x.id===save.hammer)??hammers[0],storyPower=skin.power*hammer.power,playsLeft=save.tournamentDate===today()?Math.max(0,3-save.tournamentPlays):3;
 const setTargetList=useCallback((x:Target[])=>{tr.current=x;setTargets(x)},[]);
 useEffect(()=>{try{const raw=localStorage.getItem(SAVE_KEY);if(raw){const stored={...defaultSave,...JSON.parse(raw)} as Save;if(stored.tournamentDate!==today()){stored.tournamentDate=today();stored.tournamentPlays=0;stored.tournamentBest=0}setSave(stored)}const activeWallet=localStorage.getItem("bulle-active-wallet")||"";if(activeWallet){setWalletAddress(activeWallet);setPlayerProfile(readLocalProfile(activeWallet))}}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(SAVE_KEY,JSON.stringify(save))},[ready,save]);
 useEffect(()=>{let alive=true;const load=()=>fetch("/api/rewards/pool",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then((x:RewardPool)=>{if(alive)setRewardPool(x)}).catch(()=>{});void load();const timer=window.setInterval(load,60000);return()=>{alive=false;window.clearInterval(timer)}},[]);
 useEffect(()=>()=>{if(musicTimerR.current!==null)window.clearInterval(musicTimerR.current);void audioR.current?.close()},[]);
 const finish=useCallback(()=>{if(!playR.current)return;playR.current=false;setPlaying(false);setTargetList([]);setFlash("ROUND COMPLETE");const final=sr.current,currentMode=modeR.current;setSave(old=>{if(currentMode!=="story")return {...old,tournamentDate:today(),tournamentPlays:(old.tournamentDate===today()?old.tournamentPlays:0)+1,tournamentBest:Math.max(old.tournamentDate===today()?old.tournamentBest:0,final)};const rewards=Math.floor(final*.3),progress=final-rewards;return {...old,bullPoints:old.bullPoints+progress,rewardPoints:old.rewardPoints+rewards,totalPoints:old.totalPoints+final,storyGames:old.storyGames+1,storyBest:Math.max(old.storyBest,final)}})},[setTargetList]);
 useEffect(()=>{if(!playing)return;const x=setInterval(()=>{const left=Math.max(0,Math.ceil(GAME_SECONDS-(Date.now()-startR.current)/1000));setTime(left);if(!left)finish()},100);return()=>clearInterval(x)},[playing,finish]);
 useEffect(()=>{if(!playing)return;const x=setInterval(()=>{const elapsed=(Date.now()-startR.current)/1000,free=HOLES.filter(h=>!tr.current.some(t=>t.hole===h));if(!free.length)return;const k=chooseKind(elapsed),ttl=k==="fast"?600:k==="gold"?720:Math.max(800,1400-elapsed*7);setTargetList([...tr.current,{id:idR.current++,hole:free[Math.floor(Math.random()*free.length)],kind:k,hp:base[k].hp,born:Date.now(),ttl}])},530);return()=>clearInterval(x)},[playing,setTargetList]);
 useEffect(()=>{if(!playing)return;const x=setInterval(()=>{const now=Date.now(),expired=tr.current.filter(t=>now-t.born>=t.ttl);if(!expired.length)return;setTargetList(tr.current.filter(t=>now-t.born<t.ttl));if(expired.some(t=>t.kind!=="ally")){cr.current=0;setCombo(0);lr.current--;setLives(Math.max(0,lr.current));setFlash("MISSED!");if(lr.current<=0)finish()}},80);return()=>clearInterval(x)},[playing,finish,setTargetList]);
 function begin(){if(!playerProfile){setFlash("WALLET & USERNAME REQUIRED");if(walletAddress)setProfileWallet(walletAddress);else setWalletPickerOpen(true);return}if(mode==="tournament"&&playsLeft<=0){setFlash("DAILY RUNS USED");return}setArenaIndex(Math.floor(Math.random()*3));modeR.current=mode;sr.current=cr.current=chr.current=0;lr.current=3;startR.current=Date.now();playR.current=true;setScore(0);setCombo(0);setCharge(0);setLives(3);setTime(60);setFlash(mode==="story"?"STORY START":"TOURNAMENT RUN");setTargetList([]);setPlaying(true)}
 function hit(t:Target){if(!playR.current)return;setImpact(t.hole);window.setTimeout(()=>setImpact(null),260);if(t.kind==="ally"){sr.current=Math.max(0,sr.current-50);setScore(sr.current);setTargetList(tr.current.filter(x=>x.id!==t.id));cr.current=0;setCombo(0);lr.current--;setLives(Math.max(0,lr.current));setFlash("PROTECT BULLE!");if(lr.current<=0)finish();return}if(t.hp>1){setTargetList(tr.current.map(x=>x.id===t.id?{...x,hp:x.hp-1,born:Date.now(),ttl:700}:x));setFlash(`${t.hp-1} HIT LEFT!`);return}cr.current++;const comboPower=Math.min(3,1+Math.floor(cr.current/6)*.25),gear=modeR.current==="story"?storyPower:1,earned=Math.round(base[t.kind].points*comboPower*gear);sr.current+=earned;chr.current=Math.min(100,chr.current+(t.kind==="gold"?30:10));setScore(sr.current);setCombo(cr.current);setCharge(chr.current);setFlash(t.kind==="gold"?`GOLD +${earned}`:`SMASH +${earned}`);setTargetList(tr.current.filter(x=>x.id!==t.id))}
 function unleash(){if(chr.current<100)return;const bears=tr.current.filter(t=>t.kind!=="ally"),bonus=Math.round((bears.reduce((a,t)=>a+base[t.kind].points,0)+50)*(modeR.current==="story"?storyPower:1));sr.current+=bonus;chr.current=0;setScore(sr.current);setCharge(0);setFlash(`STAMPEDE +${bonus}`);setTargetList(tr.current.filter(t=>t.kind==="ally"));navigator.vibrate?.([80,40,120])}
 function toggleMusic(){if(musicOn){if(musicTimerR.current!==null)window.clearInterval(musicTimerR.current);musicTimerR.current=null;setMusicOn(false);return}const ctx=audioR.current??new window.AudioContext();audioR.current=ctx;void ctx.resume();const melody=[146.83,174.61,196,220,196,174.61,164.81,130.81,146.83,196,233.08,220,196,174.61,146.83,130.81];const playNote=()=>{const now=ctx.currentTime,step=musicStepR.current++,freq=melody[step%melody.length],osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=step%4===0?"sawtooth":"triangle";osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(step%4===0?.055:.035,now+.025);gain.gain.exponentialRampToValueAtTime(.0001,now+.32);osc.connect(gain).connect(ctx.destination);osc.start(now);osc.stop(now+.34);if(step%4===0){const bass=ctx.createOscillator(),bg=ctx.createGain();bass.type="square";bass.frequency.value=freq/2;bg.gain.setValueAtTime(.028,now);bg.gain.exponentialRampToValueAtTime(.0001,now+.42);bass.connect(bg).connect(ctx.destination);bass.start(now);bass.stop(now+.44)}};playNote();musicTimerR.current=window.setInterval(playNote,330);setMusicOn(true)}
 function buy(item:Item,type:"skin"|"hammer"){const owned=type==="skin"?save.ownedSkins:save.ownedHammers;if(owned.includes(item.id)){setSave(o=>({...o,[type]:item.id}));return}if(save.bullPoints<item.cost)return;setSave(o=>type==="skin"?{...o,bullPoints:o.bullPoints-item.cost,skin:item.id,ownedSkins:[...o.ownedSkins,item.id]}:{...o,bullPoints:o.bullPoints-item.cost,hammer:item.id,ownedHammers:[...o.ownedHammers,item.id]})}
 const profileText=`BULLE Bear Smash — ${playerProfile?.username||"CyberBull"} · Level ${level} ${rankFor(level)} | ${save.totalPoints} total points | Story best ${save.storyBest}`;
 function shareX(){const url=`https://x.com/intent/post?text=${encodeURIComponent(profileText+"\n\nEnter the BULLE Arena 🐂\nhttps://bullecoin.io/bull-runner")}`;const opened=window.open(url,"_blank","noopener,noreferrer");if(!opened)window.location.assign(url)}
 async function requestReward(provider=walletProvider,profile=playerProfile){
  if(!profile){setClaimMessage("CONNECT WALLET AND CREATE A USERNAME FIRST");setWalletPickerOpen(true);return}
  if(!provider){setClaimMessage("CONNECT YOUR WALLET TO SIGN THE REQUEST");setWalletPickerOpen(true);return}
  if(!provider.signMessage){setClaimMessage("THIS WALLET DOES NOT SUPPORT MESSAGE SIGNING");return}
  if(save.rewardPoints<1000){setClaimMessage("A MINIMUM OF 1,000 RP IS REQUIRED");return}
  setClaimBusy(true);setClaimMessage("PREPARING FREE WALLET SIGNATURE...");
  try{
   const challengeResponse=await fetch("/api/runner/challenge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({wallet:profile.wallet})});const challenge=await challengeResponse.json();if(!challengeResponse.ok)throw new Error(challenge.error||"Challenge failed");
   const signed=await provider.signMessage(new TextEncoder().encode(challenge.message),"utf8"),raw=signed instanceof Uint8Array?signed:signed.signature;
   const response=await fetch("/api/rewards/claim",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({wallet:profile.wallet,username:profile.username,nonce:challenge.nonce,message:challenge.message,signature:bs58.encode(raw),rewardPoints:save.rewardPoints,totalPoints:save.totalPoints,storyGames:save.storyGames,storyBest:save.storyBest})});
   const result=await response.json();if(!response.ok)throw new Error(result.error||"Request failed");localStorage.setItem(`bulle-reward-claim:${profile.wallet}:${today()}`,result.claimId);setSave(old=>({...old,rewardPoints:Math.max(0,old.rewardPoints-Number(result.rewardPoints||0))}));setClaimMessage(`PAID · ${Number(result.requestedBulle).toLocaleString(undefined,{maximumFractionDigits:0})} BULLE · ${String(result.txSignature||"").slice(0,8)}...`);
  }catch(error){setClaimMessage(error instanceof Error?error.message.toUpperCase():"REQUEST FAILED")}finally{setClaimBusy(false)}
 }
 function loadCardImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error(`Unable to load ${src}`));image.src=src})}
 async function downloadCard(){try{setFlash("BUILDING PROFILE IMAGE...");const [bullSheet,hammerSheet]=await Promise.all([loadCardImage("/game-assets/bull-skins.png"),loadCardImage("/game-assets/hammers.png")]),canvas=document.createElement("canvas");canvas.width=1200;canvas.height=675;const c=canvas.getContext("2d");if(!c)throw new Error("Canvas unavailable");const g=c.createLinearGradient(0,0,1200,675);g.addColorStop(0,"#28100d");g.addColorStop(1,skin.color+"66");c.fillStyle=g;c.fillRect(0,0,1200,675);c.strokeStyle=skin.color;c.lineWidth=8;c.strokeRect(24,24,1152,627);c.fillStyle=skin.color;c.font="900 34px Arial";c.fillText("BULLE // OFFICIAL FIGHTER PROFILE",70,95);c.fillStyle="#fff";c.font="900 82px Arial";c.fillText(rankFor(level),70,205);c.font="900 46px Arial";c.fillText(`LEVEL ${level}`,70,280);c.font="700 29px Arial";c.fillText(`${skin.name}  ×  ${hammer.name}`,70,345);c.fillStyle="#d5c5b7";c.fillText(`TOTAL POINTS  ${save.totalPoints.toLocaleString()}`,70,430);c.fillText(`STORY BEST  ${save.storyBest.toLocaleString()}`,70,480);c.fillText(`TOURNAMENT BEST  ${save.tournamentBest.toLocaleString()}`,70,530);c.fillStyle=skin.color;c.font="900 30px Arial";c.fillText(`STORY POWER ×${storyPower.toFixed(2)}`,70,600);const positions:Record<string,[number,number]>={steel:[0,0],neon:[1,0],solana:[0,1],gold:[1,1],rookie:[0,0],turbo:[1,0],titan:[0,1],stampede:[1,1]},[bullX,bullY]=positions[skin.id],[hammerX,hammerY]=positions[hammer.id],bullW=bullSheet.naturalWidth/2,bullH=bullSheet.naturalHeight/2,hammerW=hammerSheet.naturalWidth/2,hammerH=hammerSheet.naturalHeight/2;c.save();c.beginPath();c.arc(935,310,205,0,Math.PI*2);c.clip();c.drawImage(bullSheet,bullX*bullW,bullY*bullH,bullW,bullH,730,105,410,410);c.restore();c.drawImage(hammerSheet,hammerX*hammerW,hammerY*hammerH,hammerW,hammerH,930,430,190,190);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error("Image export failed")),"image/png")),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`BULLE-profile-${playerProfile?.username||"CyberBull"}-level-${level}.png`;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1500);setFlash("PROFILE IMAGE DOWNLOADED")}catch(error){console.error(error);setFlash("IMAGE DOWNLOAD FAILED")}}
 const storyLeaders=useMemo(()=>[{name:"YOU",value:save.totalPoints},{name:"ArenaWolf",value:2400},{name:"NeonHorn",value:1800}].sort((a,b)=>b.value-a.value),[save.totalPoints]);const tournamentLeaders=useMemo(()=>[{name:"YOU",value:save.tournamentBest},{name:"BearBreaker",value:2950},{name:"GreenStampede",value:2480}].sort((a,b)=>b.value-a.value),[save.tournamentBest]);
 if(!ready)return null;
 return <main className={`${s.shell} ${s[`world${arenaIndex}`]}`}><header className={s.header}><a className={s.homeButton} href="/">← HOME</a><div className={s.brand}><span>BEAR</span> SMASH <small>V24</small></div><nav>{(["play","ranking","workshop","profile"] as Tab[]).map(x=><button key={x} className={tab===x?s.active:""} onClick={()=>setTab(x)}>{x==="play"?"PLAY":x==="ranking"?"RANKING":x==="workshop"?"WORKSHOP":"PROFILE"}</button>)}</nav><button className={`${s.musicButton} ${musicOn?s.musicActive:""}`} onClick={toggleMusic} aria-pressed={musicOn}>{musicOn?"♫ MUSIC ON":"♪ MUSIC OFF"}</button><button className={s.playerIdentity} onClick={()=>setWalletPickerOpen(true)}><small>{playerProfile?.username||"PLAYER PROFILE"}</small><b>{playerProfile?`${playerProfile.wallet.slice(0,4)}...${playerProfile.wallet.slice(-4)}`:"CONNECT WALLET"}</b></button><div className={s.wallet}><small>BULL / REWARD</small><b>{save.bullPoints.toLocaleString()} / {save.rewardPoints.toLocaleString()}</b></div></header>
 {tab==="play"&&<section><div className={s.modeBar}><button className={mode==="story"?s.selected:""} onClick={()=>!playing&&setMode("story")}><b>STORY</b><span>Progress, equipment and levels</span></button><button className={mode==="tournament"?s.selected:""} onClick={()=>!playing&&setMode("tournament")}><b>TOURNAMENT</b><span>{playsLeft}/3 runs available today</span></button><div><small>{mode==="story"?"STORY POWER":"FAIR POWER"}</small><b>×{mode==="story"?storyPower.toFixed(2):"1.00"}</b></div></div><div className={s.stats}><div><small>SCORE</small><b>{score}</b></div><div><small>COMBO</small><b>×{Math.min(3,1+Math.floor(combo/6)*.25).toFixed(2)}</b></div><div><small>TIME</small><b>{time}s</b></div><div><small>ENERGY</small><b>{"●".repeat(lives)}{"○".repeat(3-lives)}</b></div></div><div className={`${s.arena} ${s[`arena${arenaIndex}`]} ${s[`hammer-${hammer.id}`]}`}><div className={s.flash} key={flash}>{flash}</div><div className={`${s.cyberBull} ${s[skin.id]}`}><img src="/bulle-arena-hero.png" alt="Cyber Bull fighter"/><b>{skin.name}</b></div><div className={s.grid}>{HOLES.map(h=>{const t=targets.find(x=>x.hole===h);return <button key={h} className={s.hole} onPointerDown={()=>t&&hit(t)}>{impact===h&&<span className={s.hammerSwing} aria-hidden="true"/>}{t&&<span className={`${s.target} ${s[t.kind]}`}><i/><i/><b>{base[t.kind].label}</b><em>{t.kind==="tank"?`${t.hp}×`:`+${base[t.kind].points}`}</em></span>}</button>})}</div>{!playing&&<div className={s.overlay}><small>{mode==="story"?`LEVEL ${level} // ${rankFor(level)}`:`DAILY TOURNAMENT // ${playsLeft} RUNS LEFT`}</small><h1>{mode==="story"?"STORY MODE":"TOURNAMENT"}</h1><p>{mode==="story"?"Earn Bull Points, unlock equipment and evolve your fighter profile.":"Three daily runs. Your best score enters the tournament ranking. All gear is equalized."}</p><button onClick={begin} disabled={mode==="tournament"&&playsLeft<=0}>{mode==="tournament"&&playsLeft<=0?"COME BACK TOMORROW":"ENTER THE RING"}</button></div>}</div><div className={s.charge}><div><span style={{width:`${charge}%`}}/></div><button disabled={charge<100||!playing} onClick={unleash}>UNLEASH STAMPEDE</button></div><div className={s.legend}><span className={s.cBear}>BEAR +10</span><span className={s.cFast}>FAST +25</span><span className={s.cTank}>TANK +18</span><span className={s.cGold}>GOLD +100</span><span className={s.cAlly}>PROTECT BULLE</span></div></section>}
 {tab==="ranking"&&<section className={s.panel}><div className={s.panelTitle}><div><small>SEASON CONTROL</small><h2>RANKINGS & TIMER</h2></div><div className={s.reset}><small>DAILY RUNS RESET</small><b>00:00 LOCAL</b><span>{playsLeft}/3 available</span></div></div><div className={s.rankGrid}><Ranking title="TOURNAMENT" subtitle="Main weekly reward pool" rows={tournamentLeaders}/><Ranking title="STORY PROGRESSION" subtitle="Smaller community reward" rows={storyLeaders}/></div><p className={s.beta}>Local beta data. Global wallet rankings and real rewards activate only after server anti-cheat validation.</p></section>}
 {tab==="workshop"&&<section className={s.panel}><div className={s.panelTitle}><div><small>CYBER BULL GARAGE</small><h2>SKINS & HAMMERS</h2></div><div className={s.balance}><small>AVAILABLE</small><b>{save.bullPoints} BP</b></div></div><Shop title="BULL SKINS" items={skins} owned={save.ownedSkins} equipped={save.skin} balance={save.bullPoints} buy={x=>buy(x,"skin")}/><Shop title="HAMMERS" items={hammers} owned={save.ownedHammers} equipped={save.hammer} balance={save.bullPoints} buy={x=>buy(x,"hammer")}/><article className={s.nextChapter}><small>CONTINUOUS STORY PROGRESSION</small><h3>THE HERD KEEPS EVOLVING</h3><p>Your level and points continue after the current collection is complete. New chapters, Bull skins and hammers can be added without resetting your fighter.</p></article></section>}
 {tab==="profile"&&<section className={s.panel}><div className={`${s.profileCard} ${s[skin.id]} ${s[`hammer-${hammer.id}`]}`}><div><small>OFFICIAL FIGHTER PROFILE</small><h2>{playerProfile?.username||rankFor(level)}</h2><b>{rankFor(level)} · LEVEL {level}</b><p>{skin.name} · {hammer.name}</p><div className={s.profileStats}><span>TOTAL <b>{save.totalPoints}</b></span><span>STORY BEST <b>{save.storyBest}</b></span><span>REWARD POINTS <b>{save.rewardPoints}</b></span><span>POWER <b>×{storyPower.toFixed(2)}</b></span></div></div><img src="/bulle-arena-hero.png" alt="Cyber Bull profile"/></div><div className={s.rewardVault}><div><small>AUTOMATIC REWARD VAULT</small><h3>{rewardPool?`${rewardPool.payerBalanceBulle.toLocaleString(undefined,{maximumFractionDigits:0})} BULLE READY`:"CHECKING PAYOUT WALLET..."}</h3><p>1,000 RP = USD $0.10 · Daily limit USD $2. Sign once and receive BULLE automatically after onchain confirmation.</p><code>{rewardPool?`${rewardPool.payerWallet.slice(0,6)}...${rewardPool.payerWallet.slice(-6)} · ${rewardPool.payerBalanceSol.toFixed(3)} SOL FOR FEES`:"SOLANA RPC PENDING"}</code></div><strong>{save.rewardPoints.toLocaleString()} RP</strong><button disabled={claimBusy||save.rewardPoints<1000||!rewardPool?.payerFunded||!rewardPool?.payoutEnabled} onClick={()=>void requestReward()}>{claimBusy?"SENDING BULLE...":!rewardPool?.payoutEnabled?"AUTOMATIC REWARDS PAUSED":rewardPool?.payerFunded?"REDEEM FOR BULLE":"PAYOUT WALLET PENDING"}</button>{claimMessage&&<em>{claimMessage}</em>}</div><div className={s.profileActions}><button onClick={()=>setWalletPickerOpen(true)}>{playerProfile?"CHANGE WALLET / USERNAME":"CONNECT WALLET & CREATE USERNAME"}</button><button onClick={shareX}>SHARE ON X</button><button onClick={downloadCard}>DOWNLOAD PROFILE IMAGE</button></div><p className={s.profileHelp}>70% of Story points unlock progression. 30% become Reward Points. Automatic rewards are limited to USD $2 per wallet per UTC day and confirmed on Solana before points are deducted.</p></section>}
 {walletPickerOpen&&<WalletPicker onClose={()=>setWalletPickerOpen(false)} onConnected={(provider,address)=>{localStorage.setItem("bulle-active-wallet",address);setWalletProvider(provider);setWalletAddress(address);setWalletPickerOpen(false);const existing=readLocalProfile(address);if(existing)setPlayerProfile(existing);else setProfileWallet(address)}}/>}
 {profileWallet&&<PlayerProfileSetup wallet={profileWallet} onSaved={profile=>{localStorage.setItem("bulle-active-wallet",profile.wallet);setWalletAddress(profile.wallet);setPlayerProfile(profile);setProfileWallet("")}} onClose={()=>setProfileWallet("")}/>} 
 </main>
}
function Ranking({title,subtitle,rows}:{title:string;subtitle:string;rows:{name:string;value:number}[]}){return <article className={s.ranking}><small>{subtitle}</small><h3>{title}</h3>{rows.map((r,i)=><div key={r.name}><span>#{i+1}</span><b>{r.name}</b><strong>{r.value.toLocaleString()}</strong></div>)}</article>}
function Shop({title,items,owned,equipped,balance,buy}:{title:string;items:Item[];owned:string[];equipped:string;balance:number;buy:(x:Item)=>void}){return <div className={`${s.shop} ${title.includes("SKIN")?s.skinShop:s.hammerShop}`}><h3>{title}</h3><div>{items.map(x=>{const has=owned.includes(x.id),on=equipped===x.id;return <article key={x.id} style={{"--item":x.color} as React.CSSProperties}><span className={s.itemVisual}>{title.includes("SKIN")?"🐂":"🔨"}</span><small>{x.rarity}</small><h4>{x.name}</h4><b>STORY ×{x.power.toFixed(2)}</b><button disabled={!has&&balance<x.cost} onClick={()=>buy(x)}>{on?"EQUIPPED":has?"EQUIP":`${x.cost} BP`}</button></article>})}</div></div>}
