"use client";
import bs58 from "bs58";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { createRunnerState,isGrounded,RUNNER,RunnerState,stepRunner } from "@/lib/runnerEngine";
type Phantom={isPhantom?:boolean;connect():Promise<{publicKey:{toString():string}}>;signMessage(m:Uint8Array,d?:"utf8"|"hex"):Promise<{signature:Uint8Array}>};
declare global{interface Window{solana?:Phantom}}
type Entry={wallet:string;nickname:string;best_score:number};type Active={runId:string;runToken:string;seed:number;startedAt:string};
const short=(v:string)=>`${v.slice(0,4)}...${v.slice(-4)}`;
export default function BullRunner(){const canvas=useRef<HTMLCanvasElement|null>(null),img=useRef<HTMLImageElement|null>(null),frame=useRef<number|null>(null),state=useRef<RunnerState>(createRunnerState(1)),acc=useRef(0),prev=useRef(0),pending=useRef(false),jumps=useRef<number[]>([]),active=useRef<Active|null>(null);const [wallet,setWallet]=useState(""),[nickname,setNickname]=useState("CyberBull"),[score,setScore]=useState(0),[status,setStatus]=useState<"ready"|"authorizing"|"running"|"validating"|"over">("ready"),[message,setMessage]=useState(""),[accepted,setAccepted]=useState<boolean|null>(null),[board,setBoard]=useState<Entry[]>([]);const top=useMemo(()=>board.slice(0,5),[board]);
const load=useCallback(async()=>{try{const r=await fetch("/api/runner/leaderboard",{cache:"no-store"});if(r.ok){const j=await r.json();setBoard(j.leaderboard||[]);}}catch{}},[]);
useEffect(()=>{const i=new Image();i.src="/bulle-logo.jpg";img.current=i;load();const t=setInterval(load,60000);return()=>clearInterval(t);},[load]);
const draw=useCallback(()=>{const c=canvas.current,x=c?.getContext("2d");if(!c||!x)return;const s=state.current,g=x.createLinearGradient(0,0,0,RUNNER.height);g.addColorStop(0,"#020402");g.addColorStop(1,"#071407");x.fillStyle=g;x.fillRect(0,0,RUNNER.width,RUNNER.height);x.strokeStyle="rgba(141,255,47,.08)";for(let q=0;q<RUNNER.width;q+=48){x.beginPath();x.moveTo(q,0);x.lineTo(q,RUNNER.height);x.stroke();}for(let q=0;q<RUNNER.height;q+=48){x.beginPath();x.moveTo(0,q);x.lineTo(RUNNER.width,q);x.stroke();}x.fillStyle="rgba(141,255,47,.12)";x.fillRect(0,RUNNER.groundY,RUNNER.width,RUNNER.height-RUNNER.groundY);x.strokeStyle="#8dff2f";x.lineWidth=3;x.beginPath();x.moveTo(0,RUNNER.groundY);x.lineTo(RUNNER.width,RUNNER.groundY);x.stroke();for(const o of s.obstacles){const y=RUNNER.groundY-o.height;if(o.type==="bear"){x.font="38px Arial";x.fillText("🐻",o.x,y+38);}else{x.fillStyle="#ff5656";x.fillRect(o.x+9,y,o.width-18,o.height);}}if(img.current?.complete){x.save();x.beginPath();x.arc(RUNNER.bullX+35,s.bullY+35,35,0,Math.PI*2);x.clip();x.drawImage(img.current,RUNNER.bullX,s.bullY,70,70);x.restore();}x.fillStyle="#8dff2f";x.font="700 20px Arial";x.fillText(`SCORE ${s.score}`,24,36);},[]);
const submit=useCallback(async()=>{if(!active.current)return;setStatus("validating");setMessage("Server is replaying your run...");try{const r=await fetch("/api/runner/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({runId:active.current.runId,runToken:active.current.runToken,jumpTicks:jumps.current,claimedScore:state.current.score})});const j=await r.json();if(!r.ok||!j.accepted){setAccepted(false);setMessage(j.error||"Score rejected");}else{setAccepted(true);setScore(j.score);setMessage("Verified score accepted globally.");await load();}}catch{setAccepted(false);setMessage("Validation unavailable");}finally{setStatus("over");active.current=null;}},[load]);
const loop=useCallback((time:number)=>{if(status!=="running"){draw();return;}if(!prev.current)prev.current=time;acc.current+=Math.min(100,time-prev.current);prev.current=time;while(acc.current>=RUNNER.fixedStepMs){const s=state.current,want=pending.current;if(want&&isGrounded(s))jumps.current.push(s.tick);stepRunner(s,want);pending.current=false;acc.current-=RUNNER.fixedStepMs;if(s.collided){setScore(s.score);draw();submit();return;}}setScore(state.current.score);draw();frame.current=requestAnimationFrame(loop);},[draw,status,submit]);
useEffect(()=>{if(status==="running")frame.current=requestAnimationFrame(loop);return()=>{if(frame.current)cancelAnimationFrame(frame.current);};},[loop,status]);
const jump=useCallback(()=>{if(status==="running")pending.current=true;},[status]);useEffect(()=>{const k=(e:KeyboardEvent)=>{if(e.code==="Space"||e.code==="ArrowUp"){e.preventDefault();jump();}};addEventListener("keydown",k);return()=>removeEventListener("keydown",k);},[jump]);useEffect(()=>draw(),[draw]);
async function connect(){const p=window.solana;if(!p?.isPhantom){setMessage("Phantom not detected");return;}try{const r=await p.connect();setWallet(r.publicKey.toString());setMessage("Wallet connected. No transaction requested.");}catch{setMessage("Connection cancelled");}}
async function start(){const p=window.solana;if(!wallet||!p?.isPhantom){setMessage("Connect Phantom first");return;}setStatus("authorizing");setAccepted(null);setMessage("Sign the free verification message");try{const cr=await fetch("/api/runner/challenge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({wallet})}),c=await cr.json();if(!cr.ok)throw new Error(c.error);const signed=await p.signMessage(new TextEncoder().encode(c.message),"utf8");const sr=await fetch("/api/runner/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({wallet,nickname,nonce:c.nonce,message:c.message,signature:bs58.encode(signed.signature)})}),r=await sr.json();if(!sr.ok)throw new Error(r.error);active.current=r;state.current=createRunnerState(r.seed);jumps.current=[];acc.current=0;prev.current=0;pending.current=false;setScore(0);setMessage("Verified run started");setStatus("running");}catch(e){setStatus("ready");setMessage(e instanceof Error?e.message:"Authorization cancelled");}}
function share(){const t=["🐂 I completed a verified Bull Runner run!","",`Score: ${score}`,"Can you beat me?","","https://bullecoin.io/#bull-runner","","#BULLE #Solana #BullRunner"].join("\n");open(`https://x.com/intent/post?text=${encodeURIComponent(t)}`,"_blank");}
return <section className="runnerSection" id="bull-runner"><div className="contentWidth"><p className="sectionLabel">04 / BULL RUNNER VERIFIED BETA</p><div className="runnerHeader"><div><h2>RUN.<span>VERIFY. RANK.</span></h2><p>Official runs use a free wallet signature and deterministic server replay.</p></div><div className="runnerSecurityBadge"><small>SERVER CONTROLS</small><strong>DETERMINISTIC REPLAY</strong><span>Wallet signature · rate limit · one-time run token</span></div></div><div className="runnerLayout"><div className="runnerGamePanel"><div className="runnerControls"><input value={nickname} onChange={e=>setNickname(e.target.value)} maxLength={18}/><button onClick={connect}>{wallet?short(wallet):"CONNECT PHANTOM"}</button><button onClick={start} disabled={["authorizing","running","validating"].includes(status)}>{status==="authorizing"?"SIGN MESSAGE":status==="validating"?"VALIDATING":status==="running"?"RUNNING":"START VERIFIED RUN"}</button></div><div className="runnerCanvasWrap" onClick={jump} onTouchStart={e=>{e.preventDefault();jump();}}><canvas ref={canvas} width={RUNNER.width} height={RUNNER.height}/>{status!=="running"&&<div className="runnerOverlay"><strong>{status==="validating"?"VALIDATING RUN":status==="over"?(accepted?"SCORE ACCEPTED":"RUN COMPLETE"):"BULL RUNNER"}</strong><span>{status==="over"?`Score: ${score}`:"Connect Phantom and start a verified run"}</span>{status==="over"&&<><button onClick={start}>RUN AGAIN</button><button className="runnerShareButton" onClick={share}>SHARE SCORE ON X</button></>}</div>}</div><div className="runnerGameFooter"><span>Score: {score}</span><span>{wallet?`Wallet: ${short(wallet)}`:"Wallet required"}</span><span>{accepted===true?"Verified":accepted===false?"Rejected / not ranked":"Awaiting run"}</span></div>{message&&<p className="runnerWalletMessage">{message}</p>}</div><aside className="runnerSidebar"><div className="runnerPrizeCard"><small>WEEKLY CREATOR FEES CHAMPIONSHIP</small><h3>TOP 5 SHARE 30%</h3><ol><li><span>1ST</span><strong>10%</strong></li><li><span>2ND</span><strong>7%</strong></li><li><span>3RD</span><strong>5.5%</strong></li><li><span>4TH</span><strong>4%</strong></li><li><span>5TH</span><strong>3.5%</strong></li></ol><p>Keep real payouts disabled until official rules and finalist review are published.</p></div><div className="runnerLeaderboard"><div className="runnerLeaderboardTitle"><strong>GLOBAL TOP 5</strong><small>Current UTC week</small></div>{top.length?<ol>{top.map((e,i)=><li key={e.wallet}><span>#{i+1}</span><div><strong>{e.nickname}</strong><small>{short(e.wallet)}</small></div><b>{e.best_score}</b></li>)}</ol>:<p>No verified scores yet.</p>}</div></aside></div><div className="runnerRules"><strong>VALIDATION CONTROLS</strong><p>The server recreates every obstacle and jump, validates score, collision and duration, and rate-limits official runs. Finalists still require manual review before prizes.</p></div></div></section>}
