export const RUNNER = { width: 960, height: 420, groundY: 330, bullX: 110, bullSize: 70, fixedStepMs: 1000 / 60, gravity: 0.72, jumpVelocity: -12.8, maxTicks: 60 * 180 } as const;
export type RunnerObstacle = { x:number; width:number; height:number; type:"bear"|"candle" };
export type RunnerState = { tick:number; bullY:number; velocityY:number; speed:number; score:number; collided:boolean; nextSpawnTick:number; rngState:number; obstacles:RunnerObstacle[] };
function random(s:RunnerState){let x=s.rngState|0;x^=x<<13;x^=x>>>17;x^=x<<5;s.rngState=x>>>0;return s.rngState/4294967296;}
function schedule(s:RunnerState){s.nextSpawnTick=s.tick+Math.max(48,100-Math.floor(s.speed*3))+35+Math.floor(random(s)*75);}
export function createRunnerState(seed:number):RunnerState{const s={tick:0,bullY:RUNNER.groundY-RUNNER.bullSize,velocityY:0,speed:6,score:0,collided:false,nextSpawnTick:90,rngState:seed>>>0||1,obstacles:[]} as RunnerState;schedule(s);return s;}
export function isGrounded(s:RunnerState){return s.bullY>=RUNNER.groundY-RUNNER.bullSize-.5;}
export function stepRunner(s:RunnerState,jump:boolean){if(s.collided||s.tick>=RUNNER.maxTicks)return s;if(jump&&isGrounded(s))s.velocityY=RUNNER.jumpVelocity;s.velocityY+=RUNNER.gravity;s.bullY+=s.velocityY;if(s.bullY>=RUNNER.groundY-RUNNER.bullSize){s.bullY=RUNNER.groundY-RUNNER.bullSize;s.velocityY=0;}s.speed=Math.min(14,6+s.tick/1500);if(s.tick>=s.nextSpawnTick){const type=random(s)>.5?"bear":"candle";s.obstacles.push({x:RUNNER.width+25,width:type==="bear"?52:34,height:type==="bear"?54:76,type});schedule(s);}for(const o of s.obstacles)o.x-=s.speed;s.obstacles=s.obstacles.filter(o=>o.x+o.width>-20);const b={x:RUNNER.bullX+10,y:s.bullY+8,w:RUNNER.bullSize-20,h:RUNNER.bullSize-12};s.collided=s.obstacles.some(o=>{const y=RUNNER.groundY-o.height;return b.x<o.x+o.width&&b.x+b.w>o.x&&b.y<y+o.height&&b.y+b.h>y;});s.tick++;s.score=s.tick;return s;}
export function replayRun(seed:number,jumps:number[]){const s=createRunnerState(seed),set=new Set(jumps);while(!s.collided&&s.tick<RUNNER.maxTicks)stepRunner(s,set.has(s.tick));return s;}
